version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user_cloud
      POSTGRES_PASSWORD: password_cloud
      POSTGRES_DB: cloud_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: java_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cloud_db
      SPRING_DATASOURCE_USERNAME: user_cloud
      SPRING_DATASOURCE_PASSWORD: password_cloud
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
        - "repo.maven.apache.org:146.75.124.215"
        - "repo1.maven.org:146.75.124.215"

  frontend:
    build: ./frontend
    container_name: react_web
    ports:
      - "3002:80"
    depends_on:
      - backend

  # Mobile App Preview (Ionic/Vue)
  mobile-ionic:
    build: ./mobile-ionic
    container_name: ionic_mobile
    ports:
      - "8100:8100"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./mobile-ionic:/app
      - /app/node_modules

  tileserver:
    image: maptiler/tileserver-gl:latest
    container_name: tileserver
    restart: unless-stopped
    ports:
      - "8085:8080"
    volumes:
      - ./map-data:/data
    command: --no-cors --verbose

volumes:
  postgres_data: